// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIT0L5uxsKDIBtcwtUXGZ5NFSDksLgIk',
    appId: '1:108685119172:web:9f06730e933d15532e8391',
    messagingSenderId: '108685119172',
    projectId: 'androidmadrasasystem',
    authDomain: 'androidmadrasasystem.firebaseapp.com',
    storageBucket: 'androidmadrasasystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0iZs8w_NzR_hax7OJjr7t2-6x1zgZols',
    appId: '1:108685119172:android:8fc0fd04e6b352632e8391',
    messagingSenderId: '108685119172',
    projectId: 'androidmadrasasystem',
    storageBucket: 'androidmadrasasystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJsub63eWN8SFwyhzeNGJAHQHNZ1eCwVk',
    appId: '1:108685119172:ios:501c04db8b548f032e8391',
    messagingSenderId: '108685119172',
    projectId: 'androidmadrasasystem',
    storageBucket: 'androidmadrasasystem.firebasestorage.app',
    iosBundleId: 'com.madrasa.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJsub63eWN8SFwyhzeNGJAHQHNZ1eCwVk',
    appId: '1:108685119172:ios:a4f54065d5755f312e8391',
    messagingSenderId: '108685119172',
    projectId: 'androidmadrasasystem',
    storageBucket: 'androidmadrasasystem.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgIT0L5uxsKDIBtcwtUXGZ5NFSDksLgIk',
    appId: '1:108685119172:web:d20647162d6e550e2e8391',
    messagingSenderId: '108685119172',
    projectId: 'androidmadrasasystem',
    authDomain: 'androidmadrasasystem.firebaseapp.com',
    storageBucket: 'androidmadrasasystem.firebasestorage.app',
  );
}